---

- hosts: ios
  gather_facts: false
  tasks:
  - name: invoke gather function
    include_role:
      name: network.base.resource_manager
    vars:
      action: gather
      ansible_network_os: cisco.ios.ios
      resources:
        - 'interfaces'
        - 'l2_interfaces'
        - 'l3_interfaces'