---

- name: network.base validated content
  hosts: ios
  gather_facts: no
  tasks:
      
  - name: invoke list function
    include_role:
      name: network.base.resource_manager
    vars:
      ansible_network_os: cisco.ios.ios
      action: list
