
# - name: Gather Facts
#   hosts: ios
#   gather_facts: false
#   tasks:
#   - name: BGP Manager
#     ansible.builtin.include_role:
#       name: network.bgp.run
#     vars:
#       actions:
#         - name: gather

# - name: Perform health checks
#   hosts: ios
#   gather_facts: false
#   vars:
#   tasks:
#   - name: BGP Manager
#     ansible.builtin.include_role:
#       name: network.bgp.run
#     vars:
#       actions:
#         - name: health_check
#           vars:
#             details: True
#             checks:
#               - name: all_neighbors_up
#               - name: all_neighbors_down
#               - name: min_neighbors_up
#                 min_count: 1

- name: Persist the facts into host vars
  hosts: ios
  gather_facts: false
  tasks:
  - name: BGP Manager
    ansible.builtin.include_role:
      name: network.bgp.run
    vars:
      actions:
        - name: persist
          inventory_directory: './inventory'

- name: Deploy host vars facts
  hosts: ios
  gather_facts: false
  tasks:
  - name: BGP Manager
    include_role:
      name: network.bgp.run
    vars:
      actions:
        - name: deploy